// ECOS 시계열 정의. 기획서 §4-0의 시장 대시보드 지표(수출기업向 — 국고채 3년 제외).
// statCode/itemCode는 2026-07-14 실호출로 검증됨.
// historyStart: 실제 ECOS 데이터가 존재하는 최초 시점(백필 기준일).
export const SERIES = [
  {
    id: "FX_USD_KRW",
    label: "원/달러",
    statCode: "731Y001",
    itemCode: "0000001",
    cycle: "D",
    unit: "원",
    historyStart: "1980-01-04",
    prefix: "ECOS",
    category: "fx",
  },
  {
    id: "FX_JPY_KRW",
    label: "원/엔(100엔)",
    statCode: "731Y001",
    itemCode: "0000002",
    cycle: "D",
    unit: "원",
    historyStart: "1977-04-01",
    prefix: "ECOS",
    category: "fx",
  },
  {
    id: "FX_EUR_KRW",
    label: "원/유로",
    statCode: "731Y001",
    itemCode: "0000003",
    cycle: "D",
    unit: "원",
    historyStart: "1999-01-04",
    prefix: "ECOS",
    category: "fx",
  },
  {
    id: "FX_CNY_KRW",
    label: "원/위안",
    statCode: "731Y001",
    itemCode: "0000053",
    cycle: "D",
    unit: "원",
    historyStart: "2016-01-04",
    prefix: "ECOS",
    category: "fx",
  },
  {
    id: "BOK_BASE_RATE",
    label: "한국은행 기준금리",
    statCode: "722Y001",
    itemCode: "0101000",
    cycle: "D",
    unit: "연%",
    historyStart: "1999-05-06",
    prefix: "ECOS",
    category: "rate",
  },
];
